export const defualt_and_defined_routes = {
    default_ciphers : '/',
    dashboard_routes : '/dashboard',
    workflows_route : '/workflows',
    settings_route :'/settings' ,
    connections_route : '/connections',
    billing_route : '/billings',
    templates_route:'/templates',
    previous_logs :'/logs',
    products_route : "/products",
    pricing_route : "/pricing",
    clients_route : "/clients",
    resources_route : "/resources",
    documentation_route : "/documentation",
    enterprise_route : "/enterprise",
}